version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
    open-pull-requests-limit: 5
    cooldown:
      semver-patch-days: 7
      semver-minor-days: 7
      semver-major-days: 14
