name: 'Setup'
description: 'Sets up the Node.js environment with pnpm, configures caching for dependencies, and installs project packages.'
runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v4.0.0
    - name: Set up Node ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        cache: 'pnpm'
        node-version: ${{ matrix.node-version }}
    - name: Cache node_modules
      uses: actions/cache@v4
      id: cache-node-modules
      with:
        path: node_modules
        key: ${{ matrix.node-version }}-modules-${{ hashFiles('pnpm-lock.yaml') }}
        restore-keys: |
          ${{ matrix.node-version }}-modules-
    - name: Install Dependencies
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: pnpm i
      shell: bash

