name: 'Setup'
description: 'Sets up the Node.js environment with pnpm, configures caching for dependencies, and installs project packages.'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4  # v3 -> v4
    - uses: pnpm/action-setup@v4.0.0
    
    - name: Set up Node ${{ matrix.node-version }}
      uses: actions/setup-node@v4  # v3 -> v4
      with:
        cache: 'pnpm'
        node-version: ${{ matrix.node-version }}
    
    - name: Cache pnpm
      uses: actions/cache@v4  # v3 -> v4
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-${{ matrix.node-version }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}  # Added runner.os
        restore-keys: ${{ runner.os }}-${{ matrix.node-version }}-pnpm-  # Added runner.os
    
    - name: Cache node_modules
      uses: actions/cache@v4  # v3 -> v4
      id: cache-node-modules
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ matrix.node-version }}-modules-${{ hashFiles('pnpm-lock.yaml') }}  # Added runner.os
        restore-keys: |
          ${{ runner.os }}-${{ matrix.node-version }}-modules-
    
    - name: Install Dependencies
      if: steps.cache-node-modules.outputs.cache-hit != 'true'  # Only install if cache missed
      run: pnpm i --frozen-lockfile  # Added --frozen-lockfile for safety
      shell: bash